window.gc2dest = {
    "type": "FeatureCollection",
    "features": [
{"type": "Feature", properties: {"gid": 1, speciale: "\u00d8jenl\u00e6ge", navn: "Burton David Kamille & Anna-kirsten Kamille", samlet_adresse: "Algade 19b, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 2, speciale: "\u00d8jenl\u00e6ge", navn: "Poul Lange Gr\u00f8n", samlet_adresse: "Gammeltorp 2, 7700 Thisted"}},
{"type": "Feature", properties: {"gid": 3, speciale: "\u00d8jenl\u00e6ge", navn: "Flemming Krebs S\u00f8rensen", samlet_adresse: "H l. Plads 9, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 4, speciale: "\u00d8jenl\u00e6ge", navn: "Frederikshavn \u00d8jenl\u00e6gecenter Ulrich Langagergaard", samlet_adresse: "Hangaardsvej 13, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 5, speciale: "\u00d8jenl\u00e6ge", navn: "Niels Kalstrup", samlet_adresse: "John F. Kennedysplads 45, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 6, speciale: "\u00d8jenl\u00e6ge", navn: "Ghassan Muhammed", samlet_adresse: "M\u00f8lle\u00e5 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 7, speciale: "\u00d8jenl\u00e6ge", navn: "\u00d8jencenter Nord  v\/Henrik Vorum & Tommy B. Poulsen", samlet_adresse: "N\u00f8rrebro 12, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 8, speciale: "\u00d8jenl\u00e6ge", navn: "Mette Kaas-Hansen", samlet_adresse: "N\u00f8rregade 2D, 9330 Dronninglund"}},
{"type": "Feature", properties: {"gid": 9, speciale: "\u00d8jenl\u00e6ge", navn: "Tom T. Thorsen", samlet_adresse: "S\u00f8ndergade 22, 9600 Aars"}},
{"type": "Feature", properties: {"gid": 10, speciale: "\u00d8jenl\u00e6ge", navn: "Speciall\u00e6ge Masoud Arani", samlet_adresse: "Slotsgade 27, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 11, speciale: "\u00d8jenl\u00e6ge", navn: "Kim Frost , \u00f8jenl\u00e6ge, dr.med.", samlet_adresse: "Strandparken 48, 7900 Nyk\u00f8bing M"}},
{"type": "Feature", properties: {"gid": 12, speciale: "\u00d8jenl\u00e6ge", navn: "Vendsyssel \u00D8jenklinik", samlet_adresse: "Tolstrupvej 91, 9700 Br\u00f8nderslev"}},
{"type": "Feature", properties: {"gid": 13, speciale: "\u00d8jenl\u00e6ge", navn: "Niels Busted", samlet_adresse: "Tordenskjoldsgade 9E, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 14, speciale: "\u00d8jenl\u00e6ge", navn: "Jens Bach Andersen Aps.", samlet_adresse: "Vesterbro 63, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 15, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Henrik Geneflk Aps.", samlet_adresse: "\u00d8ster\u00e5gade 13, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 16, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Henrik Fr\u00f8lund Korsholm Aps.", samlet_adresse: "Asylgade 13, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 17, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8re- n\u00e6se- halsklinikken Budolfi Plads", samlet_adresse: "Budolfi Plads 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 18, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Merete Ipsen", samlet_adresse: "Dag Hammarskj\u00f8lds Gade 4, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 19, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Christian Schou Aps.", samlet_adresse: "Danmarksgade 25B, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 20, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Henrik Arentoft Aps.", samlet_adresse: "Jernbanegade 1A, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 21, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8re-N\u00e6se-halsklinik. v\/Claus Jacobsen", samlet_adresse: "Kraghsvej 1, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 22, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8re- N\u00e6se- Halsklinikken, Thisted", samlet_adresse: "Sydhavnsvej 15, 7700 Thisted"}},
{"type": "Feature", properties: {"gid": 23, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8rel\u00e6ge Br\u00f8nderslev,                         Henning Wolf", samlet_adresse: "Tolstrupvej 91, 9700 Br\u00f8nderslev"}},
{"type": "Feature", properties: {"gid": 24, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Speciall\u00e6geselskabet Jette B\u00f8nneland Madsen Aps.", samlet_adresse: "Ved Stranden 22, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 25, speciale: "An\u00e6stesiologi", navn: "Finn Redke", samlet_adresse: "Hobrovej 42A, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 26, speciale: "An\u00e6stesiologi", navn: "Ivan Bo Nielsen", samlet_adresse: "Kirkegade 6, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 27, speciale: "An\u00e6stesiologi", navn: "Anders Baastrup Aps.", samlet_adresse: "Roldgade1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 28, speciale: "B\u00f8rne psyk.", navn: "B\u00f8rnepsykiatrisk Klinik Nordjylland", samlet_adresse: "Teisensvej 1, 9400 N\u00f8rresundby"}},
{"type": "Feature", properties: {"gid": 29, speciale: "Banddagist", navn: "Guldb\u00e6k\/ Bundgaard", samlet_adresse: "Bispensgade 95, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 30, speciale: "Banddagist", navn: "Sahva Blyt\u00e6k", samlet_adresse: "Blyt\u00e6kkervej 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 31, speciale: "Banddagist", navn: "Bandagistcenter", samlet_adresse: "Hobrovej 76, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 32, speciale: "Banddagist", navn: "Ortho - Blatic", samlet_adresse: "John F. Kennedysplads 1F, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 33, speciale: "Banddagist", navn: "Sahva Care", samlet_adresse: "Nytorv 11, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 34, speciale: "Gyn\u00e6kolog", navn: "Morten Ring Aps.", samlet_adresse: "Dag Hammarskj\u00f8lds Gade 4, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 35, speciale: "Gyn\u00e6kolog", navn: "Anders Faurskov Nielsen", samlet_adresse: "Ved Stranden 22, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 36, speciale: "Hudl\u00e6ge (dermato-venerolog)", navn: "Thomas Hohwy", samlet_adresse: "Dag Hammarskj\u00f8lds Gade 4, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 37, speciale: "Hudl\u00e6ge", navn: "Carsten S. Mikkelsen Dermatologisk Selskab Aps.", samlet_adresse: "Bredgade 13, 9700 Br\u00f8nderslev"}},
{"type": "Feature", properties: {"gid": 38, speciale: "Hudl\u00e6ge", navn: "Hans Lomholt og Henrik S\u00f8lvsten & Hudl\u00e6gecenter Nord", samlet_adresse: "Fyrkildevej 7, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 40, speciale: "Hudl\u00e6ge", navn: "Inger Louise Wildfarg", samlet_adresse: "H l Biesgade 6, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 41, speciale: "Hudl\u00e6ge", navn: "Hudklinik Frej Studstrup", samlet_adresse: "Havnetorv 1B, 7700 Thisted"}},
{"type": "Feature", properties: {"gid": 42, speciale: "Hudl\u00e6ge", navn: "Hudl\u00e6ge klinikken Frederikshavn Helene Holmgren", samlet_adresse: "Parallelvej 29, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 43, speciale: "Intern Mediciner", navn: "Hans Chr. Hoeck", samlet_adresse: "Jernbanegade 21, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 44, speciale: "Intern Mediciner", navn: "Geert T. Espersen", samlet_adresse: "John F. Kennedysplads 1K, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 45, speciale: "Intern Mediciner", navn: "Geert T. Espersen", samlet_adresse: "Sygehusvej 6, 9460 Brovst"}},
{"type": "Feature", properties: {"gid": 46, speciale: "Kirurg", navn: "Mads Mark, Kirurisk Klinik", samlet_adresse: "Bispensgade 10, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 47, speciale: "Kirurg", navn: "Bruno Nyholm Jensen", samlet_adresse: "Ved Stranden 22, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 48, speciale: "Neurokirurg", navn: "Flemming Bang", samlet_adresse: "Brotorvet 4, 9400 N\u00f8rresundby"}},
{"type": "Feature", properties: {"gid": 49, speciale: "Neurolog", navn: "Neurologisk Speciall\u00e6geklinik Aalborg Aps", samlet_adresse: "Algade 38b, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 50, speciale: "Neurolog", navn: "Einar Bech", samlet_adresse: "Ll. Sct. Mikkelsgade 4, 8800 Viborg"}},
{"type": "Feature", properties: {"gid": 51, speciale: "Ortop\u00e6dkirurg", navn: "Bue Bak", samlet_adresse: "Lille Borgergade 27, 9400 N\u00f8rresundby"}},
{"type": "Feature", properties: {"gid": 52, speciale: "Ortop\u00e6dkirurg", navn: "S\u00f8ren Kaalund Aps.", samlet_adresse: "M\u00f8lle\u00e5 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 53, speciale: "Ortop\u00e6dkirurg", navn: "Speciall\u00e6geselskabet K. Bundgaard", samlet_adresse: "P N\u00f8rkj\u00e6rs plads 5, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 54, speciale: "Ortop\u00e6dkirurg", navn: "Ortop\u00e6dkirurgisk K. Sydhimmerland", samlet_adresse: "Smedevej 34, 9500 Hobro"}}            ]
};
