window.gc2dest = {
    "type": "FeatureCollection",
    "features": [
{"type": "Feature", properties: {"gid": 1, speciale: "\u00d8jenl\u00e6ge", navn: "Burton David Kamille & Anna-kirsten Kamille", samlet_adresse: "Algade 19b, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 2, speciale: "\u00d8jenl\u00e6ge", navn: "Poul Lange Gr\u00f8n", samlet_adresse: "Gammeltorp 2, 7700 Thisted"}},
{"type": "Feature", properties: {"gid": 3, speciale: "\u00d8jenl\u00e6ge", navn: "\u00d8jenklinikken Hobro ved Jakob S\u00f8holt", samlet_adresse: "H l Bies Plads 9, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 4, speciale: "\u00d8jenl\u00e6ge", navn: "Frederikshavn \u00d8jenl\u00e6gecenter Ulrich Langagergaard", samlet_adresse: "Hangaardsvej 13, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 5, speciale: "\u00d8jenl\u00e6ge", navn: "Niels Kalstrup", samlet_adresse: "John F. Kennedysplads 45, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 5, speciale: "\u00d8jenl\u00e6ge", navn: "Lola Gazieva", samlet_adresse: "John F. Kennedysplads 1K, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 6, speciale: "\u00d8jenl\u00e6ge", navn: "Ghassan Muhammed", samlet_adresse: "M\u00f8lle\u00e5 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 7, speciale: "\u00d8jenl\u00e6ge", navn: "\u00d8jencenter Nord  v\/Henrik Vorum & Tommy B. Poulsen", samlet_adresse: "N\u00f8rrebro 12, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 8, speciale: "\u00d8jenl\u00e6ge", navn: "Mette Kaas-Hansen", samlet_adresse: "N\u00f8rregade 2D, 9330 Dronninglund"}},
{"type": "Feature", properties: {"gid": 9, speciale: "\u00d8jenl\u00e6ge", navn: "Tom T. Thorsen", samlet_adresse: "S\u00f8ndergade 22, 9600 Aars"}},
{"type": "Feature", properties: {"gid": 10, speciale: "\u00d8jenl\u00e6ge", navn: "Speciall\u00e6ge Masoud Arani", samlet_adresse: "Slotsgade 27, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 11, speciale: "\u00d8jenl\u00e6ge", navn: "Kim Frost , \u00f8jenl\u00e6ge, dr.med.", samlet_adresse: "Strandparken 48, 7900 Nyk\u00f8bing M"}},
{"type": "Feature", properties: {"gid": 12, speciale: "\u00d8jenl\u00e6ge", navn: "Vendsyssel \u00D8jenklinik", samlet_adresse: "Tolstrupvej 91, 9700 Br\u00f8nderslev"}},
{"type": "Feature", properties: {"gid": 13, speciale: "\u00d8jenl\u00e6ge", navn: "Niels Busted", samlet_adresse: "Tordenskjoldsgade 9E, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 14, speciale: "\u00d8jenl\u00e6ge", navn: "Jens Bach Andersen Aps.", samlet_adresse: "Vesterbro 63, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 15, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Henrik Geneflk Aps.", samlet_adresse: "\u00d8ster\u00e5gade 13, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 16, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Henrik Fr\u00f8lund Korsholm Aps.", samlet_adresse: "Asylgade 13, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 17, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8re- n\u00e6se- halsklinikken Budolfi Plads", samlet_adresse: "Budolfi Plads 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 18, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Merete Ipsen", samlet_adresse: "Dag Hammarskj\u00f8lds Gade 4, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 19, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Christian Schou Aps.", samlet_adresse: "Danmarksgade 25B, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 20, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Henrik Arentoft Aps.", samlet_adresse: "Jernbanegade 1A, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 21, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8re-N\u00e6se-halsklinik. v\/Claus Jacobsen", samlet_adresse: "Kraghsvej 1, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 22, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8re- N\u00e6se- Halsklinikken, Thisted", samlet_adresse: "Sydhavnsvej 15, 7700 Thisted"}},
{"type": "Feature", properties: {"gid": 23, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "\u00d8rel\u00e6ge Br\u00f8nderslev,                         Henning Wolf", samlet_adresse: "Tolstrupvej 91, 9700 Br\u00f8nderslev"}},
{"type": "Feature", properties: {"gid": 24, speciale: "\u00d8re\/ n\u00e6se\/ hals", navn: "Speciall\u00e6geselskabet Jette B\u00f8nneland Madsen Aps.", samlet_adresse: "Ved Stranden 22, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 25, speciale: "An\u00e6stesiologi", navn: "Finn Redke", samlet_adresse: "Hobrovej 42A, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 26, speciale: "An\u00e6stesiologi", navn: "Ivan Bo Nielsen", samlet_adresse: "Kirkegade 6, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 27, speciale: "An\u00e6stesiologi", navn: "Anders Baastrup Aps.", samlet_adresse: "Roldgade 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 28, speciale: "B\u00f8rne psyk.", navn: "B\u00f8rnepsykiatrisk Klinik Nordjylland", samlet_adresse: "Teisensvej 1, 9400 N\u00f8rresundby"}},
{"type": "Feature", properties: {"gid": 29, speciale: "Banddagist", navn: "Guldb\u00e6k\/ Bundgaard", samlet_adresse: "Bispensgade 95, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 30, speciale: "Banddagist", navn: "Sahva Blyt\u00e6k", samlet_adresse: "Blyt\u00e6kkervej 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 31, speciale: "Banddagist", navn: "Bandagistcenter", samlet_adresse: "Hobrovej 76, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 32, speciale: "Banddagist", navn: "Ortho - Blatic", samlet_adresse: "John F. Kennedysplads 1F, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 33, speciale: "Banddagist", navn: "Sahva Care", samlet_adresse: "Nytorv 11, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 34, speciale: "Gyn\u00e6kolog", navn: "Morten Ring Aps.", samlet_adresse: "Dag Hammarskj\u00f8lds Gade 4, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 35, speciale: "Gyn\u00e6kolog", navn: "Anders Faurskov Nielsen", samlet_adresse: "Ved Stranden 22, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 36, speciale: "Hudl\u00e6ge", navn: "Thomas Hohwy", samlet_adresse: "Dag Hammarskj\u00f8lds Gade 4, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 37, speciale: "Hudl\u00e6ge", navn: "Carsten Sauer Mikkelsen Dermatologisk Selskab Aps.", samlet_adresse: "Tolstrupvej 91, 9700 Br\u00f8nderslev"}},
{"type": "Feature", properties: {"gid": 38, speciale: "Hudl\u00e6ge", navn: "Hans Lomholt og Henrik S\u00f8lvsten & Hudl\u00e6gecenter Nord", samlet_adresse: "Fyrkildevej 7, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 40, speciale: "Hudl\u00e6ge", navn: "Inger Louise Wildfarg", samlet_adresse: "H l Biesgade 6, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 41, speciale: "Hudl\u00e6ge", navn: "Hudklinik Frej Studstrup", samlet_adresse: "Havnetorv 1B, 7700 Thisted"}},
{"type": "Feature", properties: {"gid": 42, speciale: "Hudl\u00e6ge", navn: "Hudl\u00e6ge klinikken Frederikshavn Helene Holmgren", samlet_adresse: "Parallelvej 29, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 43, speciale: "Intern Mediciner", navn: "Hans Chr. Hoeck", samlet_adresse: "Jernbanegade 21, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 44, speciale: "Intern Mediciner", navn: "Geert T. Espersen", samlet_adresse: "John F. Kennedysplads 1K, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 45, speciale: "Intern Mediciner", navn: "Geert T. Espersen", samlet_adresse: "Sygehusvej 6, 9460 Brovst"}},
{"type": "Feature", properties: {"gid": 46, speciale: "Kirurg", navn: "Mads Mark, Kirurisk Klinik", samlet_adresse: "Bispensgade 10, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 47, speciale: "Kirurg", navn: "Bruno Nyholm Jensen", samlet_adresse: "Ved Stranden 22, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 48, speciale: "Neurokirurg", navn: "Flemming Bang", samlet_adresse: "Brotorvet 4, 9400 N\u00f8rresundby"}},
{"type": "Feature", properties: {"gid": 49, speciale: "Neurolog", navn: "Neurologisk Speciall\u00e6geklinik Aalborg Aps", samlet_adresse: "Algade 38b, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 50, speciale: "Neurolog", navn: "Einar Bech", samlet_adresse: "Hans Hartvig Seedorffs Str\u00e6de 3, 8000 Aarhus C"}},
{"type": "Feature", properties: {"gid": 51, speciale: "Ortop\u00e6dkirurg", navn: "Bue Bak", samlet_adresse: "Lille Borgergade 27, 9400 N\u00f8rresundby"}},
{"type": "Feature", properties: {"gid": 52, speciale: "Ortop\u00e6dkirurg", navn: "Ortop\u00e6dkirurgisk K. Sydhimmerland", samlet_adresse: "Smedevej 34, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 53, speciale: "Ortop\u00e6dkirurg", navn: "S\u00f8ren Kaalund Aps.", samlet_adresse: "M\u00f8lle\u00e5 1, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 54, speciale: "Ortop\u00e6dkirurg", navn: "Speciall\u00e6geselskabet K. Bundgaard", samlet_adresse: "P N\u00f8rkj\u00e6rs Pl. 5, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 55, speciale: "P\u00e6diater\/B\u00f8rnel\u00e6ge", navn: "Elise S. Jensen (b\u00f8rne)", samlet_adresse: "Boulevarden 9, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 56, speciale: "P\u00e6diater\/B\u00f8rnel\u00e6ge", navn: "Olav Bennedb\u00e6k", samlet_adresse: "Gugvej 185, 9210 Aalborg S\u00d8"}},
{"type": "Feature", properties: {"gid": 57, speciale: "P\u00e6diater\/B\u00f8rnel\u00e6ge", navn: "Zanne Larsen", samlet_adresse: "Jyllandsgade 18, 9520 Sk\u00f8rping"}},
{"type": "Feature", properties: {"gid": 58, speciale: "P\u00e6diater\/B\u00f8rnel\u00e6ge", navn: "Karen Tilma", samlet_adresse: "N\u00f8rregade 12, 9700 Br\u00f8nderslev"}},
{"type": "Feature", properties: {"gid": 59, speciale: "Praktiserende l\u00e6ge", navn: "L\u00e6gerne i Fjerritslev", samlet_adresse: "Aggersundvej 3, 9690 Fjerritslev"}},
{"type": "Feature", properties: {"gid": 60, speciale: "Praktiserende l\u00e6ge", navn: "Nordic Medicare L\u00e6geklinik", samlet_adresse: "Bredgade 130, 9490 Pandrup"}},
{"type": "Feature", properties: {"gid": 62, speciale: "Praktiserende l\u00e6ge", navn: "L\u00e6geklinikken Sulsted", samlet_adresse: "Doktorstien 5, 9381 Sulsted"}},
{"type": "Feature", properties: {"gid": 63, speciale: "Praktiserende l\u00e6ge", navn: "L\u00e6gerne i L\u00f8gst\u00f8r", samlet_adresse: "Fogedgade 3, 9670 L\u00f8gst\u00f8r"}},
{"type": "Feature", properties: {"gid": 64, speciale: "Praktiserende l\u00e6ge", navn: "L\u00e6gerne Postv\u00e6nget", samlet_adresse: "Postv\u00e6nget 1, 9440 Aabybro"}},
{"type": "Feature", properties: {"gid": 65, speciale: "Praktiserende l\u00e6ge", navn: "L\u00e6gerne Vredsted", samlet_adresse: "Stationsvej 1, 9480 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 66, speciale: "Praktiserende l\u00e6ge", navn: "Regionsklinik Brovst", samlet_adresse: "Sygehusvej 6, 9460 Brovst"}},
{"type": "Feature", properties: {"gid": 67, speciale: "Praktiserende l\u00e6ge", navn: "L\u00e6gerne Pandrup", samlet_adresse: "Torvegade 6, 9490 Pandrup"}},
{"type": "Feature", properties: {"gid": 68, speciale: "Psykiater", navn: "Kirsten Gormsen", samlet_adresse: "Bispensgade 16, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 69, speciale: "Psykiater", navn: "Lars Peter Hansen", samlet_adresse: "Danmarksgade 69B, 9900 Frederikshavn"}},
{"type": "Feature", properties: {"gid": 70, speciale: "Psykiater", navn: "Speciall\u00e6ge psykiatri Irna Mejlhede", samlet_adresse: "H. I. Biesgade 9, 9500 Hobro"}},
{"type": "Feature", properties: {"gid": 71, speciale: "Psykiater", navn: "Astrid Lykken", samlet_adresse: "Holgersgade 5B, 7900 Nyk\u00f8bing M"}},
{"type": "Feature", properties: {"gid": 72, speciale: "Psykiater", navn: "J\u00f8rn Iversen", samlet_adresse: "Dag Hammarskj\u00f8lds Gade 4, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 73, speciale: "Psykiater", navn: "Bjarne L. Christensen", samlet_adresse: "Klokkest\u00f8bergade 17, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 74, speciale: "Psykiater", navn: "Hans Henrik Wernlund", samlet_adresse: "Str\u00f8mgade 8, 9800 Hj\u00f8rring"}},
{"type": "Feature", properties: {"gid": 75, speciale: "Psykiater", navn: "Lien  og Guldb\u00e6k", samlet_adresse: "Ved stranden 11d, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 76, speciale: "Psykiater", navn: "S\u00f8ren \u00d8rnberg", samlet_adresse: "Ving\u00e5rdsgade 9, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 77, speciale: "Reumatolog", navn: "Reumatologisk Klinik", samlet_adresse: "Fyrkildevej 7, 9220 Aalborg \u00d8st"}},
{"type": "Feature", properties: {"gid": 78, speciale: "Reumatolog", navn: "Reuma Nord, v/Jens Lykkegaard Olesen", samlet_adresse: "John F. Kennedys Plads 1R, 4., 9000 Aalborg \u00d8st"}},
{"type": "Feature", properties: {"gid": 79, speciale: "Reumatolog", navn: "Merete Graakj\u00e6r Nielsen", samlet_adresse: "Morten B\u00f8rups Gade 10a, 8000 Aarhus"}},
{"type": "Feature", properties: {"gid": 80, speciale: "Reumatolog", navn: "Erik M. Gustavson", samlet_adresse: "Skt. Clemens Torv 17, 8000 Aarhus"}},
{"type": "Feature", properties: {"gid": 81, speciale: "Synsinstitut", navn: "Synsinstitutet", samlet_adresse: "Sofiendalsvej 92a, 9200 Aalborg SV"}},
{"type": "Feature", properties: {"gid": 82, speciale: "Synsprotese", navn: "Thiele", samlet_adresse: "Bispensgade 6, 9000 Aalborg"}},
{"type": "Feature", properties: {"gid": 83, speciale: "Taleinstitut", navn: "Taleinstitutet", samlet_adresse: "Borgmester J\u00f8rgensvej 2, 9000 Aalborg"}}
            ]
};
